apiVersion: v2
name: nx-cloud
version: 0.1.0
dependencies:
  - name: nx-cloud
    version: "1.2.6"
    repository: "https://nrwl.github.io/nx-cloud-helm/"
  - name: mongodb
    version: "19.1.36"
    repository: "https://charts.bitnami.com/bitnami"
  - name: valkey
    version: "6.2.12"
    repository: "https://charts.bitnami.com/bitnami"
