apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  router.yaml: |
{{ .Values.routerConfig | indent 4 }}
  supergraph.graphql: |
{{ .Values.supergraphSchema | indent 4 }}
